# Generated by Django 4.1.3 on 2022-11-15 09:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapterid', models.IntegerField(primary_key=True, serialize=False)),
                ('chaptername', models.CharField(blank=True, default='draftchaptername', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(blank=True, default='draftname', max_length=100)),
                ('coursecredits', models.IntegerField(blank=True, default=0)),
                ('courseimg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lessonid', models.IntegerField(primary_key=True, serialize=False)),
                ('lessonname', models.CharField(blank=True, default='Lessonname', max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='MCQtopic',
            fields=[
                ('MCQtopicid', models.IntegerField(primary_key=True, serialize=False)),
                ('MCQtopicname', models.CharField(blank=True, default='Lessonname', max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='mcq',
            fields=[
                ('mcqid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('option1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('opt1answ', models.BooleanField(default=False)),
                ('option2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('opt2answ', models.BooleanField(default=False)),
                ('option3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('opt3answ', models.BooleanField(default=False)),
                ('option4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('opt4answ', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='lessncontent',
            fields=[
                ('contentid', models.IntegerField(primary_key=True, serialize=False)),
                ('video', models.CharField(blank=True, default='', max_length=100)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.courses'),
        ),
        migrations.CreateModel(
            name='Assignmenttopic',
            fields=[
                ('Assignmenttopicid', models.IntegerField(primary_key=True, serialize=False)),
                ('Assignmnetname', models.CharField(blank=True, default='Lessonname', max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.chapters')),
            ],
        ),
    ]
