# Generated by Django 4.1.3 on 2022-11-19 07:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_chapters_courses_lesson_mcqtopic_mcq_lessncontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignmenttask',
            fields=[
                ('taskid', models.IntegerField(primary_key=True, serialize=False)),
                ('task', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('Feedback', models.TextField(default='Enter here')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.assignmenttopic')),
            ],
        ),
        migrations.CreateModel(
            name='mcqansw',
            fields=[
                ('mcqid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('option1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('opt1answ', models.BooleanField(default=False)),
                ('option2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('opt2answ', models.BooleanField(default=False)),
                ('option3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('opt3answ', models.BooleanField(default=False)),
                ('option4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('opt4answ', models.BooleanField(default=False)),
                ('mcqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.mcqtopic')),
            ],
        ),
        migrations.DeleteModel(
            name='mcq',
        ),
    ]
